# Generated by Django 6.0.5 on 2026-06-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0003_rename_data_added_entry_date_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="text",
            field=models.TextField(),
        ),
    ]
