name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup uv
      uses: astral-sh/setup-uv@v3
    - name: Install Dependencies
      run: uv sync
    - name: Run Tests
      run: uv run manage.py test